### ISSUE TITLE
app crash at starts after installing from play store

### ISSUE THREAD

**Issue by surbhicis** [AndreMiras/PyWallet#158]
app crash at starts after installing from play store

**Comment by AndreMiras** [comment]
Thank you for the report. I hope I get time soon to push an update

**Comment by AndreMiras** [comment]
The problem seems to be Infura suddenly made API key mandatory. I have a fix that I'll try to deploy to the app store hopefully the coming week

**Comment by AndreMiras** [comment]
I've released `2020.0524` version on the store that should hopefully fix the issue
